package com.trustledgersaas.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * GoldLoan — Represents a single gold loan (one loan per one gold item pledged).
 *
 * IMPORTANT BUSINESS RULE (confirmed by Bibi):
 * ONE LOAN PER GOLD ITEM. If a customer pledges multiple items (e.g. a chain AND
 * a ring) in one visit, the shop owner creates TWO separate loan records. Each has
 * its own Loan ID, due date, interest rate, and closure. Gold item fields live
 * directly on this entity — there is NO separate GoldItem table.
 *
 * Interest is NEVER stored as a static field. It is always computed fresh from
 * the formula in InterestCalculator every time it needs to be displayed.
 *
 * Lifecycle statuses:
 *   ACTIVE  → loan is current, not past due date
 *   OVERDUE → automatically set by daily scheduled job when due date passes
 *   CLOSED  → manually set by shop owner after full repayment + gold returned
 *   SEIZED  → manually set by shop owner when gold is seized (not returned)
 *
 * Relationships:
 * - One GoldLoan belongs to one Customer — @ManyToOne with Customer
 * - One GoldLoan belongs to one Shop — @ManyToOne with Shop (for direct querying)
 * - One GoldLoan has many Payments — @OneToMany with Payment
 * - One GoldLoan has many ReminderLogs — @OneToMany with ReminderLog
 */
@Entity
@Table(name = "gold_loans")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GoldLoan {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable loan identifier (e.g. "LN-2026-00341").
     * Auto-generated by the system when a loan is created.
     * This is what the shop owner and customer see — NOT the database ID.
     */
    @Column(nullable = false, unique = true)
    private String loanId;

    /**
     * The principal amount lent to the customer (in INR).
     * This is the actual cash given against the pledged gold item.
     */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal loanAmount;

    /**
     * Monthly interest rate as a percentage.
     * For example, 1.5 means 1.5% per month.
     * Used in the interest calculation formula (see InterestCalculator).
     */
    @Column(nullable = false, precision = 5, scale = 2)
    private BigDecimal interestRate;

    /**
     * The date the loan was created / money was disbursed.
     * MUST NOT be a past date (validated on creation — no backdating allowed).
     * This date is the starting point for all interest calculations.
     */
    @Column(nullable = false)
    private LocalDate loanDate;

    /**
     * The date by which the loan should be repaid.
     * Auto-suggested as loanDate + 3 months, but the shop owner can edit it.
     * After this date, the loan status automatically flips from ACTIVE to OVERDUE.
     */
    @Column(nullable = false)
    private LocalDate dueDate;

    /**
     * Current status of this loan.
     * ACTIVE  — loan is current, before or on due date
     * OVERDUE — past due date (set automatically by daily scheduled job)
     * CLOSED  — fully repaid, gold returned to customer (manual shop owner action)
     * SEIZED  — gold seized by shop due to non-payment (manual shop owner action)
     */
    @Column(nullable = false)
    @Builder.Default
    private String status = "ACTIVE";

    // ==================== GOLD ITEM DETAILS ====================
    // These fields describe the specific gold item pledged for THIS loan.
    // One loan = one gold item. Fields live directly here (no separate GoldItem entity).

    /**
     * Type of gold item pledged.
     * Preset options: Gold Chain, Gold Ring, Gold Bangle, Gold Necklace,
     * Gold Bracelet, Gold Earrings, Gold Coin, Others.
     * If "Others" is selected, goldItemDescription holds the custom text.
     */
    @Column(nullable = false)
    private String goldItemType;

    /** Custom description for the gold item (used when goldItemType is "Others") */
    private String goldItemDescription;

    /** Weight of the gold item in grams */
    @Column(nullable = false, precision = 8, scale = 3)
    private BigDecimal goldWeight;

    /** Purity of the gold (e.g. "22K", "18K", "24K") */
    @Column(nullable = false)
    private String goldPurity;

    /** Estimated market value of the gold item in INR */
    @Column(precision = 12, scale = 2)
    private BigDecimal estimatedValue;

    // ==================== WARNING & CLOSURE FLAGS ====================

    /**
     * Flag indicating whether the 30-day seizure warning has been shown.
     * Set to true when the daily scheduler processes a loan that is 30+ days overdue.
     * When true, the customer's dashboard (Pro plan) displays a warning banner.
     */
    @Builder.Default
    private boolean seizureWarningShown = false;

    /** Timestamp when the loan was closed or seized (null while still active/overdue) */
    private LocalDateTime closedAt;

    // ==================== RELATIONSHIPS ====================

    /**
     * The customer who took this loan.
     * Many loans can belong to one customer (ManyToOne relationship).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /**
     * The shop that issued this loan.
     * Directly linked for easy querying (e.g. "get all loans for shop X").
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shop_id", nullable = false)
    private Shop shop;

    /**
     * All payments made against this loan (both cash and online).
     * One loan has many payments.
     */
    @OneToMany(mappedBy = "goldLoan", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Payment> payments = new ArrayList<>();

    /**
     * All reminder notifications that have been sent for this loan.
     * Used to prevent sending the same reminder twice.
     */
    @OneToMany(mappedBy = "goldLoan", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<ReminderLog> reminderLogs = new ArrayList<>();

    // ==================== TIMESTAMPS ====================

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
