package com.trustledgersaas.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Payment — Records a single payment transaction against a gold loan.
 *
 * Both cash payments (manually entered by shop owner) and online payments
 * (automatically recorded after Razorpay verification) are stored here
 * in the same table. They appear together in chronological order in the
 * payment history view.
 *
 * Each payment has a unique, sequential receipt number that is used in
 * the PDF receipt generation.
 *
 * Relationships:
 * - Many Payments belong to one GoldLoan — @ManyToOne with GoldLoan
 */
@Entity
@Table(name = "payments")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The gold loan this payment is applied to.
     * Many payments can be made against one loan (ManyToOne relationship).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "gold_loan_id", nullable = false)
    private GoldLoan goldLoan;

    /** The amount paid in this specific transaction (in INR) */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    /** The date this payment was made / recorded */
    @Column(nullable = false)
    private LocalDate paymentDate;

    /**
     * How the payment was made.
     * Possible values: CASH, ONLINE_UPI, ONLINE_CARD, ONLINE_NETBANKING, ONLINE_WALLET
     * Cash payments are entered manually by the shop owner.
     * Online payments are determined by what the customer chose in Razorpay Checkout.
     */
    @Column(nullable = false)
    private String paymentMode;

    /** Razorpay payment ID — only set for online payments (null for cash) */
    private String razorpayPaymentId;

    /** Razorpay order ID — only set for online payments (null for cash) */
    private String razorpayOrderId;

    /**
     * Unique, sequential receipt number (e.g. "REC-00001").
     * Generated by the system and used in PDF receipt generation.
     */
    @Column(unique = true)
    private String receiptNumber;

    /** Optional note added by the shop owner when recording a cash payment */
    @Column(length = 500)
    private String note;

    /** When this payment record was created in the database */
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
